// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbeULNua54cx2QsoLRINvDomO5P19za2Y',
    appId: '1:355483350178:web:5bf85643668b9b965453fb',
    messagingSenderId: '355483350178',
    projectId: 'nectar-a5cc2',
    authDomain: 'nectar-a5cc2.firebaseapp.com',
    storageBucket: 'nectar-a5cc2.appspot.com',
    measurementId: 'G-9W89GV6ZRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-rNwsWle3nU5wo-TMH03j056OhKjjJQ',
    appId: '1:355483350178:android:1e894223fe0868855453fb',
    messagingSenderId: '355483350178',
    projectId: 'nectar-a5cc2',
    storageBucket: 'nectar-a5cc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq-TV4wZljfy8AoS59493IY_EPuyRmgLg',
    appId: '1:355483350178:ios:c46ab4746b98099a5453fb',
    messagingSenderId: '355483350178',
    projectId: 'nectar-a5cc2',
    storageBucket: 'nectar-a5cc2.appspot.com',
    iosClientId: '355483350178-39b82c23mu7aom49c17qra78d0shhaf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nectar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq-TV4wZljfy8AoS59493IY_EPuyRmgLg',
    appId: '1:355483350178:ios:f374d9485b2d0ea55453fb',
    messagingSenderId: '355483350178',
    projectId: 'nectar-a5cc2',
    storageBucket: 'nectar-a5cc2.appspot.com',
    iosClientId: '355483350178-jn6utcov35d7bh4r0lsvgiim4bkc07ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.nectar.RunnerTests',
  );
}
